moment/luxon

- src/datetime.js
- src/impl/util.js
- test/datetime/create.test.js
Restrict input to Dates; produce invalid DateTimes from invalid Dates.
> Fix DateTime.fromJSDate input handling

- src/datetime.js
- test/datetime/getters.test.js
Adds the convenience getters as discussed in #48
> Adds weekday & month convenience getters

- docs/why.md
Love the project's ethos — the focus on immutability by itself is a huge win, especially when working with developers unfamiliar with moment's ~bugs~ idiosyncrasies. Looking forward to using this in upcoming projects!
> [docs] Fix typo + cleanup trailing whitespace.

- src/datetime.js
- src/impl/regexParser.js
- test/datetime/format.test.js
- test/datetime/regexParse.test.js
- attempt to fix https://github.com/moment/luxon/issues/79
- tests included
> feat: add fromSQL

- readme.md
Hello! Luxon looks great. First link I tried was the installation guide, which didn't seem to work. Just thought I'd try to help out!
> Fix README installation guide link

- src/impl/formatter.js
- test/datetime/toFormat.test.js
`DateTime.fromISO('2017-12-01T00:00:00').toFormat('ha')` should output 12am, not 0am.
> Midnight should return 12 for h, not 0

- benchmarks/datetime.js
Change `this` scope.
```
console.log('Fastest is ' + undefined.filter('fastest').map('name'));
^
TypeError: Cannot read property 'filter' of undefined
```
> Don't use Arrow Function

- tasks/build.js
> (build) mangle top-level names

- src/datetime.js
- src/impl/util.js
- test/datetime/math.test.js
> Fix math at the end of months

- src/datetime.js
- src/impl/conversions.js
- src/impl/util.js
- test/datetime/misc.test.js
> Add weeksInWeekYear Method

- src/luxon.js
Fixes https://github.com/moment/luxon/issues/226
> Added exposes for specific zones.

- src/datetime.js
- src/formats.js
- test/datetime/tokenParse.test.js
Removes deprecated code from the 2.0 branch and fixes lint errors so that the build passes
> Remove deprecated code

- docs/moment.md
- src/datetime.js
- test/datetime/transform.test.js
Patch for #246 .
I'll saw you comment, and plan to add test(s) later (probably tomorrow). Please note that by some reason a lot of existing tests are failed on my machine.
Could you please meanwhile briefly look on patch and provide a feedback what else should be done?
> add toMillis method

- src/datetime.js
- test/datetime/create.test.js
> Implemented fromMillis() to verify args

- src/zones/IANAZone.js
- test/datetime/zone.test.js
Fix for https://github.com/moment/luxon/issues/302, also I couldn't run tests on my local machine. so didn't check whether all tests are passing.
> bug fix for Etc/GMT timezones

- docs/validity.md
- src/datetime.js
- src/duration.js
- src/errors.js
- src/impl/conversions.js
- src/impl/invalid.js
- src/impl/locale.js
- src/impl/zoneUtil.js
- src/interval.js
- src/zones/invalidZone.js
- test/datetime/invalid.test.js
- test/interval/create.test.js
- test/interval/parse.test.js
> reworking invalid reporting

- src/datetime.js
- src/duration.js
- test/datetime/typecheck.test.js
- test/duration/typecheck.test.js
Fixed `isDateTime` and `isDuration` to make them return `false` instead of `undefined`.
> Fix Issue 376

- docs/matrix.md
Closes https://github.com/moment/luxon/issues/190
See https://github.com/yahoo/date-time-format-timezone/commit/a9b0126b3797313f96175f40a98cc4ec73b2652f
> DateTime format pollyfill bug fixed

- src/interval.js
- test/interval/many.test.js
As discussed in https://github.com/moment/luxon/issues/386, here's my first try!
> mapEndpoints implementation + test + docs

- docs/math.md
- docs/matrix.md
- package-lock.json
- src/datetime.js
- src/impl/locale.js
- src/zone.js
Just odds and ends I came across when updating the types in DefinitelyTyped.
> Doc typos.

- src/datetime.js
- test/datetime/relative.test.js
> fixed issue "toRelativeCalendar shows today twice when using setZone"

- src/impl/locale.js
Closes https://github.com/moment/luxon/issues/439
> Fix typo in PolyNumberFormatter

- test/helpers.js
Just a run of `npm run lint!`.
Should be merge first, so that other PRs can ignore these file changes
> Fix linting errors in test/helpers.js

- docs/math.md
Hey all!  Just reading into the library and noticed a spelling mistake.
Thanks for all the hard work!
> fixed spelling mistake

- docs/zones.md
- package-lock.json
- src/datetime.js
- src/impl/zoneUtil.js
- test/datetime/zone.test.js
- test/helpers.js
Reverts moment/luxon#475
See comments in the associated ticket; I want to think about this a bit more
> Revert "Add `system` alias to LocalZone in normalizeZone"

- src/impl/regexParser.js
- test/duration/parse.test.js
> fixed ISO week format issue

- src/datetime.js
- test/datetime/format.test.js
> fixed ISO [±YYYYY] formating

- src/zones/IANAZone.js
> fix doc for IANAZone.isValidZone

- docs/math.md
> docs: fixed typo mistake

- src/duration.js
`null` is typeof "object"
Fix #516
> Fix inconclusive error message

- src/impl/formatter.js
- src/impl/tokenParser.js
- test/datetime/tokenParse.test.js
> Add ability to parse some of localized macro format tokens

- src/duration.js
- src/impl/util.js
- test/duration/math.test.js
> Add Duration#mapUnits

- src/datetime.js
- src/impl/tokenParser.js
- test/datetime/tokenParse.test.js
This PR probably has missing things, but it works so this should be a good start 
This is an attempt to support #595
> Add quarter parsing support

- src/datetime.js
> Typo in unit normalization

- src/datetime.js
- src/impl/formatter.js
- test/datetime/format.test.js
> Add support for ISO basic format to DateTime#toISO

- src/datetime.js
Closes https://github.com/moment/luxon/issues/678
> Add more details to exception message

- src/interval.js
- test/interval/info.test.js
> fix Interval.hasSame behaviour for empty intervals

- package.json
> Mark the package as side-effects-free

- test/datetime/relative.test.js
Seems that this will fail one day per month
> RelativeTime test fails on last day of the month

- docs/math.md
> Update wording around date equality test

- package-lock.json
Running `npm-install` after a clean clone updates the lock file
> Update package-lock.json after npm install

- docs/intl.md
> Typo fixed

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
added template for bugs and feature requests
> Update issue templates. Fixes #759

- src/datetime.js
Weeks always start on Mondays.
> Update startOf/endOf documentation. Fixes #801

- package-lock.json
- package.json
- tasks/build.js
This is an attempt to resolve #771.
> Fix ES6 minify

- docs/math.md
- src/datetime.js
- test/datetime/misc.test.js
This is an attempt to resolve #584
> Fix hasSame unit comparison

- src/impl/locale.js
- test/datetime/format.test.js
> Remove fixed-offset formatting workaround #866

- src/impl/diff.js
- test/datetime/diff.test.js
Hello,
Made the changes required in PR #778 review
> Add quarters to diff fix #776

- docs/math.md
"seem reflect what people mean" -> "seem to reflect what people mean"
> added a "to" for grammar :)

- docs/math.md
> Fix small typo in math docs

- src/datetime.js
- src/zones/IANAZone.js
- test/zones/IANA.test.js
Fixed [Issue 856](https://github.com/moment/luxon/issues/856)
> 856: fixed Etc/GMT0 yields Invalid DateTime

- scripts/bootstrap.js
- src/impl/regexParser.js
- test/datetime/regexParse.test.js
> fix ISO year-ordinal strings with offsets

- test/duration/info.test.js
fix for issue #1046  Useless test in test/duration/info.test.js 
my first contribution to luxon :)
> remove irrelevant duration test fix issue 1046

- src/datetime.js
- test/datetime/format.test.js
Fixes https://github.com/moment/luxon/issues/941
> Add includeOffsetSpace option to toSQLTime and toSQL

- src/datetime.js
I noticed this duplicate comment while I was learning about DateTime and figured it was worth a small PR!
> removing duplicate comment in datetime.js

- demo/demo.css
adds background color to rows on demo to make it simple to match example to it's result.
> style(demo): add background on hover

- src/impl/regexParser.js
- test/datetime/regexParse.test.js
> Wednesday support for RFC 850

- src/datetime.js
- src/duration.js
- src/interval.js
Fixed the JSDocs for static members to fix the links in API docs raised in #1175
> Fixed JSDocs for static members

- src/datetime.js
- test/datetime/format.test.js
A more convenient way to get no milliseconds of sql time.
> SQL time support trim milliseconds

- src/datetime.js
- test/datetime/format.test.js
Reverts moment/luxon#1400.
Oops need to reconsider this.
> Revert "SQL time support trim milliseconds"

- docs/zones.md
I found document of timezone incorrect and therefore I created this PR.
Also this problem has been already reported by an issue below.
https://github.com/moment/luxon/issues/1392
> fix: Documentation for timezone

- site/index.html
This quick PR adds a search bar to the main documentation website (cf. #1475)
> Add search to the main docs site

- src/interval.js
> Update interval.js doc per #742

- src/impl/locale.js
- src/impl/util.js
- src/zone.js
- src/zones/IANAZone.js
- src/zones/fixedOffsetZone.js
Had to look at the sources to get an idea of what the IANA zones and the UTC zones are really doing. Maybe this helps.
> Added some JS doc for time zones
