- package.json
Normal commit hooks often require modifying files within the .git
directory manually. However, `husky` and `pre-commit` together make it
so you don't have to do anything special to run prettier against files
automatically as they are being committed. This ensures that any file
changed is automatically updated when committed.
- Add husky and precommit to the package, along with a precommit script
that will run prettier for any staged file
Note that this is the process that prettier [recommends here](https://github.com/prettier/prettier#pre-commit-hook). This addresses https://github.com/icambron/luxon/issues/27
> Make prettier run on precommit hooks automatically

- package.json
Only include the generated cjs file in the npm package (exclude sites, site, src etc.). This removed tens of megabytes from the npm package. Note that package.json, changelog.md, license.txt and readme.md are not listed, since they are always included by npm publish.
> Don’t publish unused files to npm.

- src/impl/regexParser.js
- test/duration/parse.test.js
The `PnW` format for durations was not supported.
> Add support for ISO week duration

- src/impl/regexParser.js
- src/impl/util.js
- test/datetime/regexParse.test.js
Fixes #65 
This PR will convert the fractional part of the time to nanoseconds by padding the number to 9 digits and then converting to milliseconds by dividing by 1,000,000 and rounding the result.
> Support 1-9 digits of fractional seconds parsing ISO times

- docker/Dockerfile
build and then test like normally
docker build -t icambron/luxon docker
./docker/gulp test
old: 292 MB (compressed)
new: 150MB (uncompressed), I haven't pushed to registry to see the size after compressed. an educated guess would be around 50-60MB
I also tried with `node:8-alpine` (official image) but there were a couple of failed tests. like this one.
I'm not sure if it's related to `alpine` or `bitnami:node` (based on debian).
Using `node:8-alpine` would result in even smaller image size (100MB uncompressed) but i want to clarify with you first if those tests are related.
```
FAIL  test/datetime/diff.test.js
● DateTime#diff is precise for lower order units
expect(received).toEqual(expected)
Expected value to equal:
{"hours": 2999}
Received:
{"hours": 3000}
Difference:
- Expected
+ …
```
> test: use bitnami prod image version for smaller docker test env

- docs/formatting.md
The table below clearly designates `LLLL` as standalone and `MMMM` as format,
but the example wording is flipped.
The demonstrated output was already correct though.
> fix standalone/format confusion in formatting docs

- .babelrc
- docs/install.md
- docs/matrix.md
- gulpfile.js
- package-lock.json
- package.json
- site/demo/global-filled.html
- site/index.html
- src/luxonFilled.js
A first stab at #58:
* Separate `cjs-browser` and `node` builds and use the `browser` field in `package.json`
* Explicitly support Node >= 6
* Use `preset-env` and be explicit
* Remove polyfills from all the builds
* Add an additional `global-filled` build
* Fix missing IE polyfill in that build
Remaining questions:
* I left all the browser builds as 'last 2 major versions'. That's probably right but maybe Webpackers will use Babel anyway and just want ES6 wrapped in CJS modules? I could just turn compilation off for that build.
* Exactly what versions am I supporting now (i.e. what are "2 major versions")?
Todo:
> Reorganize build

- package.json
Add module entry to package.json.
This way webpack or rollup can use the ES6 module instead of the transpiled ES5 version from babel which includes a lot of shimed code.
If module import is supported the `src/luxon.js` file gets imported otherwise it falls back to `build/node/index.js` when using `require`.
This will save quite a few bytes in the final bundle.
See: https://github.com/rollup/rollup/wiki/pkg.module
> Feature: module

- src/duration.js
if you don't put the right class here, document generator generates a wrong link to another class (DateTime class)
> fixed for correct documentation

- src/datetime.js
Luxon is looking great! Thanks for your work on this. 
Think the `toISODate()` example should show that it returns a date, not a time.
> FIx toISODate example

- src/datetime.js
It was `boolean`, should be `string|Zone` as far as I can tell
> fix type of zone in JSDoc for several constructors

- src/datetime.js
not sure why it was `object`.  Seems obvious that it should be `Date`.
> fix return type for toJSDate

- src/interval.js
Just a quick spelling update for `interrogation`, noticed on the [interval docs](https://moment.github.io/luxon/docs/class/src/interval.js~Interval.html).
> docs: jsdoc interrogation spelling

- src/info.js
- The property describing timezone support is `zones`, not `timezones`.
- The example uses `feature` instead of `features`
> Fix documentation of Info.features()

- src/interval.js
Add mention about the null value when intersection is empty.
The null may not be the best solution (causes null pointers by surprise) but at least it should be mentioned.
> Update Interval.intersection API documentation

- src/datetime.js
Adds a closing curly brace in the DateTime#fromISO documentation.
> minor syntax fix in fromISO documentation

- docs/formatting.md
- docs/math.md
- src/datetime.js
- src/duration.js
- src/impl/formatter.js
- test/datetime/math.test.js
- test/datetime/toFormat.test.js
- test/duration/accuracy.test.js
- test/duration/getters.test.js
Added quarter unit support in 'startOf', 'endOf' and 'plus' methods.
Added quarter formatting tokens 'q' and 'qq' -
q - single digit quarter
qq - 2 digits padded quarter
> Quarter unit support

- docs/parsing.md
Noticed this incorrect description while reading the docs.
> Fix incorrect format description in docs

- package.json
It's not used in sources.
This is critical for me because I can't install deps when I'm on a local network with a custom npm registry. `full-icu` runs a `post-install` script that tries to install additional deps, but it doesn't respect a custom registry.
> Move full-icu to dev deps

- src/datetime.js
- src/duration.js
- test/datetime/proto.test.js
- test/duration/proto.test.js
- test/interval/proto.test.js
Updates that allow Luxon classes to be expanded in the React dev tools. This addresses [#182](https://github.com/moment/luxon/issues/182)
> Ensure prototype getters can be addressed without throwing

- package.json
Hello! Thanks for this wonderful library.
This is more of a suggested PR, since [ember-luxon](https://github.com/willrax/ember-luxon) exists.
Essentially, I would like to import luxon directly into my Ember application, so I can keep up to date with the most recent versions of luxon without depending on another package to be published. The change here adds an AMD output, which would allow Ember apps / addons to directly import luxon into their application without running rollup. I understand that adding this build file will result in some bloat in the npm tarball, so I've added that info below:
| Before | After |
|--------|------|
| 410704 bytes | 532358 bytes |
This adds ~100K to the npm tarball.
Once again, thanks for this library ❤️
> Include AMD build in npm tarball so Ember can use luxon directly

- contributing.md
Github and many other markdown processors won't render the npm script reference table correctly as it was. This makes it render correctly in Github and others.
> fix npm script reference table for correct rendering

- src/datetime.js
I noticed the docs for `endOf('month')` did not match the behavior.
> fix endOf docs

- src/duration.js
Looks like a copy-paste error from the year unit conversion.
> Fixed month unit conversion bug

- package-lock.json
I am going to debug an issue my team may have found related to quarter math, but after running `npm install` the pacakge-lock.json file was updated. This indicates a mismatch between the versions in package.json and the lockfile. This is the result after running `npm install` on npm version 5.6.0 and Node 9.
> Update lockfile to match package.json versions

- src/zone.js
- src/zones/IANAZone.js
- src/zones/fixedOffsetZone.js
- src/zones/localZone.js
- offsetName is an instance method, not a static method
- the locale option is locale, not localeCode as previously documented
- the default value of the locale doesn't seem to be en-us as documented: there is no default value
- the classes are not private anymore as previously documented
fix #241
> fix some issues with Zone design

- src/datetime.js
I was confused by "default zone" whether it was the epoch in the default zone or the epoch in utc converted to the default zone. This clarifies it
Thank you for answering my question in https://github.com/moment/luxon/issues/267!
> Clarify fromMillis doc

- src/datetime.js
- test/datetime/transform.test.js
While BSON being off the standards track and the whole `toBSON` thing is merely a [feature](https://mongodb.github.io/node-mongodb-native/driver-articles/anintroductionto1_1and2_2.html#tobson-method) of MongoDB Node driver, this patch adds support for quite popular database solution with little effort.
EDIT: Inspired by https://github.com/boosterfuels/mongodb-moment.
> Support MongoDB serialization

- src/duration.js
- src/impl/diff.js
- test/duration/create.test.js
- test/duration/units.test.js
1. Duration.fromObject() argument verification. see: #186 
2. duration.valueOf() implemented. see: #235
> Duration.fromObject() patched and  support valueOf() for duration

- src/datetime.js
While I empathize the original comment,
1) I firmly believe that Luxon will influence an ongoing [Temporal Proposal](https://github.com/tc39/proposal-temporal) effort, thus we should keep the code base clean of harsh comments. TC39 people are doing an amazing work.
2) JavaScript had to include date API and within very tight deadline. It also was fundamental to be Java-like, to boost the adoption. `java.util.Date` had issues, but it was a very reasonable call. Without any of that, we probably wouldn't have a JavaScript community as we know it.
> Clarify a comment

- src/datetime.js
- src/duration.js
- src/impl/util.js
- src/interval.js
Resolves #276.
Node's `inspect` is fairly useful, let's try to keep it. I don't exceptionally like the solution at hand, but I have an idea how we can make it better if Node.js would support it.
> Use Symbol for Node's custom inspect

- src/datetime.js
- src/duration.js
Those assertions fail (even if we're giving actual objects) while working across different JS contexts.
Not sure that `typeof` is the best option for that though. I would just remove that check altogether since there are other subsequent checks in `fromObject` that will fail if the thing is not an object.
> Replace all `instanceof Object` checks

- src/datetime.js
- test/datetime/format.test.js
According to [RFC2822](https://www.ietf.org/rfc/rfc2822.txt) hours must be in 00-23 range. Current implementation was using `hh` which is 00-12. 
This was causing, for example a 3pm and a 3am date to print the same RFC2822 value:
```
> DateTime.local().set({ hour: 3 }).toRFC2822()
'Mon, 08 Oct 2018 03:53:26 -0400'
> DateTime.local().set({ hour: 15 }).toRFC2822()
'Mon, 08 Oct 2018 03:53:26 -0400'
```
With this change, the second one is correctly printed to have hour 15.
> Fixes DateTime.toRFC2822 using 12h instead of 24h format

- src/interval.js
- test/interval/parse.test.js
Fixes #340.
Start accepting `<start>/<duration>` and `<duration>/<end>` formats of [ISO 8601 intervals](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals).
One very minor breaking change is that an invalid input with a slash now
has a `invalidReason` of `invalid ISO format` instead of `invalid endpoints`.
```js
const i = Interval.fromISO("foo/bar");
i.invalidReason; // invalid ISO format
```
> Interval.fromISO to allow relative durations.

- src/datetime.js
Fixes #349 
Looks like one of the examples for `DateTime#toSQL` had an incorrect argument. This fixes that.
> Update DateTime#toSQL example to includeZone

- docs/formatting.md
- docs/parsing.md
- src/datetime.js
- test/datetime/create.test.js
- test/datetime/transform.test.js
This pull request adds `toSeconds` and `fromSeconds` methods for working with Unix timestamps. 
Now, I saw that https://github.com/moment/luxon/pull/319 added support for timestamps inside the `.toFormat` function, but didn't add explicit timestamp support. And, I've read the contribution guidelines, which state that:
> Luxon shouldn't contain simple conveniences that bloat the library to save callers a couple lines of code. Write those lines in your own code.
However, I think supporting Unix timestamps is an important use case. This is because many other systems and specifications use Unix timestamps in seconds as their primary date format. For example:
- Python's `time()`
- Ruby's `Time.now.to_i`
- Bash's `date +%s`
- C's `time(null)`
Because of this, many APIs specify timestamps in …
> Add support for Unix timestamps in seconds.

- src/datetime.js
Tested using en-US locale, which I think is what the example outputs are using.
> Fixed output examples for toLocaleString

- src/datetime.js
- src/info.js
- src/luxon.js
- test/datetime/getters.test.js
- test/info/zones.test.js
As discussed in #368 and #369, this PR adds the functionality required for using `Zone` instances.
> Make time zone functionality public

- docs/matrix.md
Hi, I was impressed that FF had no full Intl support, so I checked. It came in FF 65*, so I updated the table.
*According to MDN docs: [compatibility table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Browser_compatibility)
p.s. I'm not sure this was the right way to do this, since you mention in the contribution guide that clarifications and gotchas should be in the docstrings instead of the guides on the docs page. Feel free to close if this is not what you want.
> Make matrix reflect MDN compatibility table

- src/duration.js
- test/duration/format.test.js
from [Wikipedia](https://en.wikipedia.org/wiki/ISO_8601)
>Date and time elements including their designator may be omitted if their value is zero, and lower order elements may also be omitted for reduced precision. For example, "P23DT23H" and "P4Y" are both acceptable duration representations. **However, at least one element must be present, thus "P" is not a valid representation for a duration of 0 seconds. "PT0S" or "P0D", however, are both valid and represent the same duration.**
This PR makes it conform this description.
> fix zero duration formatting invalid value

- src/datetime.js
- src/duration.js
- src/impl/conversions.js
- src/impl/diff.js
- src/impl/english.js
- src/impl/formatter.js
- src/impl/locale.js
- src/impl/regexParser.js
- src/impl/tokenParser.js
- src/impl/zoneUtil.js
- src/info.js
- src/interval.js
- src/luxon.js
- src/luxonFilled.js
- src/settings.js
- src/zone.js
- src/zones/IANAZone.js
- src/zones/fixedOffsetZone.js
- src/zones/invalidZone.js
- src/zones/localZone.js
Put the file extension into import statements for all of the files in the src directory. This enables Luxon to be imported as a module by browsers that support the import statement. It currently works with some servers that ad the extension but not all. This should offer much faster download speeds over the HTTP/2 protocol. 
Address the issue #417
> added .js to imports

- src/impl/util.js
- test/datetime/create.test.js
- test/datetime/invalid.test.js
- test/duration/create.test.js
- test/duration/equality.test.js
Fixed issue #402 
line 3 should be same as line 2 or throw error
```javascript
const {DateTime} = require('luxon');
const dateTime = DateTime.utc(2019,1,1);
console.log(dateTime.toISO());                            // 2019-01-01T00:00:00.000Z
console.log(dateTime.plus({ minutes: 1 }).toISO());       // 2019-01-01T00:01:00.000Z
console.log(dateTime.plus({ minutes: "1" }).toISO());     // 2019-01-01T00:10:00.000Z
```
Same thing with { days: "1" } or { seconds: "1" }
`The issue was because we were performing the math operation without converting values in the number 
So if we add "1" + 0 in js it will be "10". `
> handled string values while normalizeObject

- docs/install.md
- site/demo/global.html
Fixes #434.
Adds `Math.sign` to the polyfill.io url for the global demo, and the IE install docs.
> Add Math.sign polyfill for IE

- src/impl/tokenParser.js
- test/datetime/tokenParse.test.js
Fixes issue #408 
```javascript
// 😥 Should print "Indian/Maldives", but throws exception "Invalid regular expression:
// /[/: Unterminated character class"
const { DateTime } = require('luxon');
console.log(DateTime.fromFormat('2019-01-14T11-30[Indian/Maldives]', ianaFormat, 
{ 
setZone: true 
}).zoneName);
```
> fixed special character issue in format string

- contributing.md
- src/datetime.js
- src/duration.js
- src/impl/regexParser.js
- src/impl/util.js
- test/datetime/create.test.js
- test/datetime/degrade.test.js
- test/datetime/invalid.test.js
- test/datetime/regexParse.test.js
- test/datetime/relative.test.js
- test/datetime/set.test.js
- test/duration/create.test.js
- test/duration/set.test.js
Make the `fromObject()` and `set` methods on `DateTime` and `Duration` more strict.
Invalid keys in the object parameter, as well as invalid values for units (such as `NaN`, `true` or `""`) now throw an error (or create an invalid `DateTime`). See the updated tests for details.
Various other minor changes.
> DateTime.fromObject silently accepts any wrong value #448

- docs/zones.md
- package-lock.json
- src/datetime.js
- src/impl/zoneUtil.js
- test/datetime/zone.test.js
- test/helpers.js
Add a `system` zone name alias to allow the system's default zone (LocalZone) to be used. This is required when the Luxon default zone has been modified and using `local` returns the default zone instead of the system zone.
Fixes: https://github.com/moment/luxon/issues/469
> Add `system` alias to LocalZone in normalizeZone

- src/duration.js
- test/duration/format.test.js
- test/helpers.js
From the look of the source, it looks like converting weeks => days in formatting was intentional. However, I would expect `Duration.fromISO('P1W').toISO()` to be deterministic and preserved as `P1W` and not `P7D` 🙂.
This was causing problems for me when I was taking a saved ISO duration string and deserialising it into a UI that would allow you to build a duration. When a user sets [3] [Weeks] in a form, the next time it renders, it would appear as [21] [Days].
**NB:** I ❤️ Luxon
> Adds week token to Duration's ISO formatting

- package.json
This will make `build/global/luxon.min.js` be the file that users get when loading via `jsdelivr` or `unpkg`
Closes https://github.com/moment/luxon/issues/443
> Make available via CDNs

- src/datetime.js
- test/datetime/create.test.js
fix issue : #494 
if Settings.throwOnInvalid is true, then DateTime.fromJSDate will throw error for invalid dates
> throw error on invalid date if throwOnInvalid  is true

- benchmarks/datetime.js
- src/impl/regexParser.js
This PR tweaks the internal implementation of `DateTime.fromISO()` and `DateTime.fromSQL()` such that the regexes and extractors used during parsing are created once _in advance_ and not with every invocation of these functions. This resulted in a speedup of about +25% on my machine for both functions (from ~55,000 ops/sec to ~67,000 ops/sec).
> combined regexes and extractors are created in advance to speed up fromISO() and fromSQL()

- src/datetime.js
Was missing valid arguments `quarter` and `week` for `startOf` method
> Fixed comments/documentation for startOf function

- src/impl/formatter.js
- src/impl/util.js
- src/info.js
- src/zone.js
- src/zones/IANAZone.js
- src/zones/fixedOffsetZone.js
- src/zones/invalidZone.js
- src/zones/localZone.js
- test/info/zones.test.js
- test/zones/IANA.test.js
- test/zones/fixedOffset.test.js
- test/zones/invalid.test.js
- test/zones/local.test.js
For feature request #504.
Moves the existing formatting logic from formatter.js to util.js so it can be utilized by all the zone subclasses.
@icambron I'd be happy to add docs and/or tests but I don't see any that deal with interacting with Zone instances directly, so I wasn't sure which files to update.
> Add formatOffset method to Zones.

- src/datetime.js
This pr fixes misleading docs for unit options in toRelative and toRelativeCalendar methods. 
I will also make a fix for [@types/luxon](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/luxon/index.d.ts#L24) with correct unit options.
> docs: fix toRelative unit options

- src/impl/util.js
hasIntl and hasRelative functions in src/impl/util.js are wrapped with try catch to avoid exceptions in IE11 browsers.
> exception handling added for hasIntl and hasRelative functions in src/impl/util.js

- src/datetime.js
- src/impl/english.js
- src/impl/formats.js
- src/impl/util.js
- test/datetime/degrade.test.js
With reference to this [issue](https://github.com/moment/luxon/issues/283)
- Added DATETIME_MED_WITH_WEEKDAY preset in src/datetime.js
- Added support for env without Intl in src/impl/english.js
- Added DATETIME_MED_WITH_WEEKDAY preset format in src/impl/formats.js
- Added a test case in test/datetime/degrade.test.js
>  Added DATETIME_MED_WITH_WEEKDAY preset for formatting toLocaleString

- src/datetime.js
`RelativeTimeFormat` vs ` on RelativeDateFormat`
> Fix `relative` method documentation

- src/datetime.js
Since the `year` parameters are officially optional, this hints to IDEs that it's safe to use empty calls like `DateTime.local()`.
Fixes #566.
> Mark first parameters in DateTime.local() and DateTime.utc() as optional

- src/impl/locale.js
Trying to fix #571, no easy repro case. Specs seem to imply that locale should always be defined though, but since there was already a special case for 'und'...
> Handle undefined DTF locale

- src/datetime.js
- test/datetime/math.test.js
As reported in #563 this problem occurs when with the DateTime.plus a duration of seconds is added which will result in a DateTime Object outside of the ECMA DateTime range.
Reproduction Code 
```js
const orgDate = DateTime.utc(1970,1,1,0,0,0,0); 
const maxRangeDays = 1E8 // max range of Dates in days
const secsPerDay = 24*60*60; // secs per day
// When adding Seconds
// d.invalid is null - expected to have reason "invalid input"
// d.c contains NaN - expected to be null
const d = orgDate.plus({seconds: maxRangeDays  * secsPerDay +1})
// When adding days
// e.invalid is has reason "invalid input"
// e.c contains null
const e = orgDate.plus({day: maxRangeDays  +1})
```
The reason why the seconds did not result within an invalid result is because:
datetime.js -> adjustTime 
In this function …
> Fix for invalid Datetime when not in valid ECMA DateTime range

- docs/formatting.md
The example code for `Intl.DateTimeFormat` uses the incorrect order of params for `Object.assign`
> Format override example has incorrect code

- src/datetime.js
- src/interval.js
- src/zones/fixedOffsetZone.js
ESDoc truncates summary messages after two periods, therefore the use of 'i.e.' would cause summaries to get unusually truncated. To fix this, I ran a find and replace, replacing 'i.e.' with meaning as suggested by @icambron.
This PR is in reference to #411
> Fixed truncated summary issue

- src/duration.js
- test/duration/format.test.js
This will fix #596 by handling [floating point madness](https://stackoverflow.com/questions/588004/is-floating-point-math-broken) when working with seconds and milliseconds.
> Fix Duration#toISO floating point madness

- docs/formatting.md
Small typo in documents for ISO week year(unpadded).
> Typo in ISO week year

- src/datetime.js
Example incorrectly showed toLocaleString
> Fix typo in example of toLocaleParts

- docs/install.md
Meteor has had support for npm for a few years now, and package installation and use is the same as for Webpack. Just replaced Moment with Luxon in my Meteor app, very easy transition and the reduction in bundle size is great.
> Remove Meteor from install docs

- src/impl/tokenParser.js
- test/datetime/tokenParse.test.js
Closes https://github.com/moment/luxon/issues/617
I'm getting two failing tests but I think they are unrelated.
<details>
<summary>Failing tests</summary>
</details>
I've tested it out in the browser with the line of code from that issue and it throws as it should
> Throw error when specifying 24-hour format with meridiem

- docs/validity.md
change: invalidExplantion
to: invalidExplanation
> Fix typo in validity.md markup (letter a) -

- docs/tour.md
Looking at the source code for Interval.length there is no second parameter: https://github.com/moment/luxon/blob/master/src/interval.js#L208
```
length(unit = "milliseconds") {
return this.isValid ? this.toDuration(...[unit]).get(unit) : NaN;
}
```
In this page of the docs it has `i.length('years', true)`. Maybe this is an old API? I removed it from the example here.
> Remove `true` param from Interval.length example

- src/impl/regexParser.js
- src/impl/util.js
- test/duration/parse.test.js
This PR fixes [moment/luxon#681](https://github.com/moment/luxon/issues/681).
The issue above links to a similar issue with moment ([moment/moment#2408](https://github.com/moment/moment/issues/2408)) which was resolved.
Although the [ISO 8601 duration format](https://www.digi.com/resources/documentation/digidocs/90001437-13/reference/r_iso_8601_duration_format.htm) does not mention support for a leading minus, there are many other libraries that support ISO duration parsing in this way.
The assumed rule is that a leading minus sign inverts the sign of all values.
Examples of leading-minus ISO strings and their equivalent non-leading-minus ISO strings:
-P1D == P-1D
-P5Y3M == P-5Y-3M
-P-5Y-3M == P5Y3M
-P-1W1DT13H-23M34S == P1W-1DT-13H23M-34S
> Duration from ISO leading minus

- docs/install.md
Fixes #697 
Add Object.is feature (required by at least IE10), and bump polyfill.io API version to v3
> Update polyfills in docs/install.md

- test/datetime/diff.test.js
- test/datetime/zone.test.js
Some tests require the local timezone to be "America/New_York", relying on the DST of this zone, such as :
_DateTime#diff handles fractional days as fractions of those specific days_
while 2 tests are protected by `if (DateTime.local().zoneName === "America/New_York")`
It seems more consistent to assume all tests require this specific timezone, as is done in `test/zones/local.test.js`:
```
expect(LocalZone.instance.name).toBe("America/New_York");
```
> All tests assume America/NewYork timezone

- src/duration.js
- test/duration/units.test.js
And a test to check all values are defined.
Note the conversion `toObject` in the test :
`Duration.fromObject({ seconds: Nan }).get('seconds')` returns 0, which may be considered a bug.
> Add missing values in conversion matrices

- src/duration.js
- test/duration/units.test.js
This is a serious change, but I assume the unit tests around `shiftTo` validate the non regression.
> Remove normalization in ShiftTo

- src/datetime.js
- test/datetime/math.test.js
Mixed positive and negative duration units values are merged when using `shiftTo`, resulting in unintuitive computations.
Removing the shift to milliseconds solves this problem, but then breaks computation with fractional values.
Applying the integer part on large units and convert the fractional part to milliseconds solves this issue.
> Fix for negative values in plus/minus. Fixes #645 and #669

- src/info.js
This is a tiny update to the Info docs that fixes places where 'month' was used in place of 'weekday' in the annotations for `Info.weekdays()` and `Info.weekdaysFormat()`.
> Fixed typos in docs where 'month' was used in place of 'weekday'

- src/impl/util.js
- test/zones/fixedOffset.test.js
Making a -0 offset display as "+00:00", while keeping the negative sign for other negative values.
From the [ISO 8601 web page](https://en.wikipedia.org/wiki/ISO_8601) : _"+00:00" (but not "-00:00") for London (UTC±00:00)_
> formatOffset handles signed offsets. Fixes #665

- package-lock.json
- test/datetime/format.test.js
Added these tests since I realized this behavior is probably broken in the `tsdx` branch, and these tests would have caught the error.
> Add tests around DateTime.toISO()

- src/impl/util.js
- test/datetime/format.test.js
Applied a `trunc` on the number of minutes in the offset, since that seems to be what is done in the other browsers.
Also the ISO 8601 wikipedia page does not mention fractional minutes in the format.
Note that this should be merged after #756, which affects the same line, since it will need a rebase (this commit also modified some formatting logic).
> Round minutes in timezone offset display. Fixes #724

- src/impl/regexParser.js
- test/datetime/regexParse.test.js
Simply remove the 9 digit limit in the regexp
> Support arbitrary precision in ISO milliseconds. Fixes #757

- src/impl/tokenParser.js
- test/datetime/create.test.js
- test/datetime/tokenParse.test.js
The problem was the the `es-ES` meridiem strings are _"a. m."_ and _"p. m."_, but with a **non breakable space** in the middle (char code 160). Since the input string used a regular space, it was not matched correctly.
This PR changes the RegExp to consider spaces and non breakable spaces characters interchangeably.
It also adds a `global` flag to the dots, so that they are *all* considered optional.
> fromFormat handles non breakable spaces. Fixes #714

- docs/moment.md
Hiya, was looking into proper internationalisation of durations and encountered this note in the luxon docs.
As per https://github.com/tc39/ecma402/issues/32#issuecomment-516588266, UnitFormat was merged into Unified NumberFormat, which was merged into ECMA-402 last March (2020).
Now I haven't investigated how widely it's already supported by browsers but I think this update of the documentation is at least warranted.
Should I create an issue to start preparing for a `Duration.humanize`-like method?
> UnitFormat was folded into Unified NumberFormat

- src/datetime.js
Padding type is shown as boolean which was confusing, checking the code I understand it is expected to be a number and it's rather an issue in the documentation.
> Fix DateTime.toRelative() docs padding type

- src/impl/formatter.js
I noticed that the link to http://cldr.unicode.org/translation/date-time was broken (404).
I believe the new URL is http://cldr.unicode.org/translation/date-time-1/date-time.
Seeing as I didn't change any code (only a comment) I didn't run the tests but I did run the linter.
> Fixed broken link to cldr.unicode.org

- src/impl/locale.js
I appreciate the sentiment, but this causes adoption problems in projects that scan for sensitive terminology.
> Remove profanity from comments

- src/impl/util.js
- test/datetime/format.test.js
Fixes [868](https://github.com/moment/luxon/issues/868)
> Fix padding of negative years in IsoDate

- src/impl/english.js
- test/info/listers.test.js
Fix for [#829](https://github.com/moment/luxon/issues/829).
Bug only appears when the English lists are used, hence setting the default locale in the test.
> #829: Made English Info lists immutable

- src/interval.js
- test/interval/many.test.js
Fix #848 - this bases duration calcs on the original start date rather than the start date of the previous split.
> #848: Base Interval.splitBy calcs on original start date

- src/datetime.js
Fixes documentation mishap for weekYear function (fixes #885).
> Correct example in documentation for weekYear (fixes #885).

- src/interval.js
- test/interval/many.test.js
See #927 for the justification.
Updated test to intended behavior without updating code and it failed (as intended):
```
FAIL  test/interval/many.test.js
● Interval#intersection returns null for adjacent intervals
expect(received).toBeNull()
Received: {"e": "2017-05-25T08:00:00.000-04:00", "invalid": null, "isLuxonInterval": true, "s": "2017-05-25T08:00:00.000-04:00"}
113 |
114 | test("Interval#intersection returns null for adjacent intervals", () => {
> 115 |   expect(todayFrom(5, 8).intersection(todayFrom(8, 10))).toBeNull();
|                                                          ^
116 | });
117 |
118 | test("Interval#intersection returns invalid for invalid intervals", () => {
at Object.<anonymous> (test/interval/many.test.js:115:58)
```
Updating interval.js caused the test to …
> #927: Return null when calling intersection() on abutting Intervals

- src/datetime.js
- test/datetime/set.test.js
Luxon wasn't preventing from mixing incompatible units.
Added validation.
> #859: Adding validation for mixing incompatible units

- src/datetime.js
`DateTime.local()` violated the DRY principle by using `return new DateTime({})` which is already defined in `DateTime.now()`.
So, I have fixed it by reusing the `DateTime.now()`.
> Fixed DRY principle violation in DateTime.local()

- src/impl/regexParser.js
- test/duration/parse.test.js
Add handling of negative millisecond cases to Duration.fromISO (fixes #882)
> Add duration fromISO negative millisecond handling

- src/impl/locale.js
- test/datetime/format.test.js
This fixes issues like #912 and #883.
- Instead of checking only if the range is likely supported, the zone is really tested before it is used. While this will have likely some performance impact, I cannot think of some other reliable way to do this.
- TZ used for formatting when the offset is 0 is UTC. This will fix issues like #878 because it'll revert things to the previous behaviour. It is not ideal, because if somebody uses explicit GMT it still becomes UTC, but AFAIK FixedOffsetZone doesn't hold the original name so this is the best that can be done.
> Add check for etc zone support before using for formatting

- src/zones/IANAZone.js
- test/datetime/math.test.js
To fix bug #905.
I confirmed the fix in the browser (local build):
```js
let d = luxon.DateTime.local();
let dz = d.setZone("America/Vancouver");
d.plus({seconds: 12345678901234567890});
DateTime {ts: 1.2345678902851053e+22, _zone: LocalZone, loc: Locale, invalid: Invalid, weekData: null, …}
dz.plus({seconds: 12345678901234567890});
DateTime {ts: 1.2345678902851053e+22, _zone: IANAZone, loc: Locale, invalid: Invalid, weekData: null, …}
```
> Prevent error from being thrown in IANAZone.offset

- src/datetime.js
Tiny cleanup to prevent warnings in ide's when not using all opts
> Updated JSDoc on `DateTime.fromISO`

- src/duration.js
The docs for `Duration#get` are showing the use of the named getters `like Duration#years` instead of the `get` method itself. This PR fixes that.
> [docs] Update Duration#get docs to show `get` method use

- benchmarks/datetime.js
- benchmarks/index.js
- benchmarks/info.js
- package.json
- src/datetime.js
- src/info.js
Potential fix for https://github.com/moment/luxon/issues/775 .
This allows an existing loc object to be passed into Info `months` and `weekdays` functions, to be used instead of creating a new one. The use of these in DateTime has been modified to use this option.
In a loop of 100000 uses of `DateTime.weekdayLong` this appears to be roughly twice as fast as creating a Locale each time.
> Add opt to use existing loc obj in weekdays/months

- src/datetime.js
- test/datetime/relative.test.js
This has been requested before in #579, see discussion there for more details.
My use case is that during the first minute, `.toRelative()` will print something like `1 second ago`. I'd like to avoid updating it every second (for performance purposes), and instead I'd like it to print out `0 minutes ago`. This way I can schedule updates once every minute instead of every second.
This PR adds a way to override which units are considered when formatting a relative date.
See the tests I added as well.
Fixes #579.
> feat: multiple units support in toRelative

- docs/formatting.md
As explained on https://github.com/moment/luxon/issues/565 .toSeconds() returns seconds.milliseconds to mimic UNIX system behaviour.
> .toSeconds() returns seconds.milliseconds

- docs/zones.md
The missing DST hour should end at 999 ms, not 000 ms. Amarite?
> Docs typo on DST weirdness

- src/duration.js
Fixed small typo where the closing quotation was missing inside the `fromObject` documentation inside `src/duration`
> Fixed small typo

- docs/matrix.md
Relative time formatting is now also supported in Edge and Safari, as shown in the table and at https://caniuse.com/mdn-javascript_builtins_intl_relativetimeformat
> Docs: Remove outdated note on relative time formatting support

- docs/parsing.md
Removed:
> That includes all the "macro" formats like "D" for "localized numeric date".
`D` is in the [table](https://moment.github.io/luxon/#/parsing?id=table-of-tokens) and is working, so I assume this is outdated.
`luxon.DateTime.fromFormat("22/07/2021", "D", { locale: "en-GB" }).toISO()` -> "2021-07-22T00:00:00.000-07:00"
> Remove outdated parsing tokens note

- docs/math.md
The example assumes the variable 'dur' is 1 year but doesn't show that step.
> Clarify confusing math example

- docs/moment.md
The docs seems to indicate that relative time format does not exist, but in fact it does.
> Fix unclear docs on relative time support

- src/zones/IANAZone.js
- test/zones/IANA.test.js
This addresses #973 (IANAZone.isValidZone(undefined) returns true).
`Intl.DateTimeFormat("en-US", { timeZone: zone }).format()` will succeed if `zone` is `undefined`.  `null`, and other non-`string` values for timeZone fail.
This adds a check to make sure `zone` is not undefined, as well as a few additional test cases for non-string values.
> Protect IANAZone.isValidZone from undefined

- .github/workflows/test.yml
Node 15 is no longer supported and 16 is now the "Current" version.
> Test in Node 16 instead of 15

- CONTRIBUTING.md
- docs/formatting.md
- docs/parsing.md
- src/impl/formatter.js
- src/impl/tokenParser.js
- test/datetime/toFormat.test.js
- test/datetime/tokenParse.test.js
These are the same as Moment's `SS` and `S` tokens, respectively.
Moment's [implementation](https://github.com/moment/moment/blob/e96809208c9d1b1bbe22d605e76985770024de42/src/lib/units/millisecond.js#L19-L25).
This is for Issue #965. ~~I'm not sure about how to add the support for `DateTime.fromFormat` though.~~
> Add support for formatting and parsing tokens `uu` and `uuu`

- test/datetime/tokenParse.test.js
This commit adds two positive test cases for parsing a fixed- and variable- length day-of-the-month, as well as a negative test cases which detects an `Invalid.reason: "unparsable"` when attempting to parse unpadded day-of-the-month with a fixed-length format.
> Add test cases for day-of-the-month parsing

- src/duration.js
- src/impl/regexParser.js
- src/impl/util.js
- test/duration/create.test.js
- test/duration/equality.test.js
- test/duration/flattenValues.test.js
- test/duration/format.test.js
- test/duration/getters.test.js
- test/duration/info.test.js
- test/duration/math.test.js
- test/duration/parse.test.js
- test/duration/set.test.js
- test/duration/typecheck.test.js
- test/duration/units.test.js
Improve duration with fractional support :
`Duration.fromObject({ days: 1.5 }) => { days: 1.5 }`
`Duration.fromISO("PT9.5H").toObject() => { hours: 9.5 }`
Closes #1058
Edit : I have updated this section to reflect the final result.
> Duration support for fractional duration

- benchmarks/datetime.js
- src/impl/locale.js
When formatting to UTC IANAZone.isValidZone will construct a new Intl.DateTimeFormat for each call.
> perf: Use memoized zone for universal zone validation

- src/datetime.js
- src/duration.js
- src/interval.js
- test/duration/create.test.js
This PR moves the private `friendlyDuration` function to `Duration.fromDurationLike`.
`DurationLike` is a TS interface defined [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/22d5e137fff20a3da5ba2c4937f10731a100a530/types/luxon/src/duration.d.ts#L60)
This change was suggested in #1057
Basically, no code was added, so bundle size remains the same.
This change allows to do things like this:
```ts
type Example = {
durationProp: Duration
}
const createExample = (duration: DurationLike): Example => {
return {
durationProp: Duration.fromDurationLike(duration)
}
}
const a = createExample(1000)
const b = createExample({ seconds: 5 })
// now we can compare a.durationProp and b.durationProp
```
> Add fromDurationLike method

- benchmarks/datetime.js
- src/datetime.js
- src/impl/util.js
- test/datetime/format.test.js
@gpaucot Added some commits:
1. I really wanted to push the work into `toSQLDate` and `toSQLTime`. So I set up both your fully-inlined one and my refactor and benchmarked them against each other, then tweaked mine until it was within the benchmark's noise level.
2. Admittedly, my code benefited from some tweaks to the logic, and once I backported those into the inlined code, that code got faster again. But only by a little, so I'm going to live with it.
3. I also removed some no-longer-needed code and did some other cleanup
These were the logic changes relative to your PR:
1. Turns out, we're supposed to always use 6-digit years for negative years. That's actually #951. That has a small perf advantage because it's quicker to compare `o.c.year > 9999 || o.c.year < 0` than it is to do …
> Continuation of #1097

- src/datetime.js
fixes #1109
@icambron I used the function name toUnixInteger, but toUnix I guess works too. Just let me know and I'll tweak
> Add whole second unix timestamp function

- src/duration.js
- test/datetime/diff.test.js
Fixes https://github.com/moment/luxon/issues/1050
Appears when diffing two dates and the second date is larger. We negate all units, leading to confusing values such as `-0` for units with no difference.
> Update Duration.negate() to not negate zeros

- package.json
Having `luxon` accessible in the console of https://moment.github.io/luxon/ is super useful to me -- however, it isn't available on /api-docs, where it is arguably even more useful. Many times, I've opened the console to try something in the API docs out, just to find that `luxon` isn't there. (Most of the time, I end up switching tabs back to the homepage to run it in the homepage console.) This PR injects `luxon.js` into /api-docs so it's accessible there.
> Add luxon to console in /api-docs

- src/datetime.js
Since the argument is an object, and `DateTime` is a generic term in addition to a Luxon type, I misinterpreted this to mean it would also validate strings and numbers. Maybe other people have been confused similarly.
> Clarify the isDateTime docs

- src/duration.js
- src/impl/formatter.js
- test/duration/format.test.js
Resolves #1164
(Working with casual conversion accuracy was quite confusing when writing the test. 🤯)
> feat: add week formatting token "w" for duration

- src/impl/tokenParser.js
Some languages can have spaces or non-breakable spaces in the month definition.
This lead to creating a regex with more capturing groups than it should.
For example, `tháng 3` is `mars` in Vietnamese and contains a space. (see #1169)
And if you try to parse this month using: `DateTime.fromFormat("tháng 3 2022", "MMMM yyyy", {locale: "vi-VN"})`
It will create the following regex: `/^(tháng( | )1|tháng( | )...)(\d{4})$/i`
Which has a capturing group for each space.
After this commit, it will create the following regex instead: `/^(tháng[  ]1|tháng[  ]...)(\d{4})$/i`
So it does not create additional capturing groups.
> fix: change NBSP regex to a non-matching group #1169

- package.json
- src/package.json
Importing `luxon` in a modern Node ESM project with `"type": "module"` causes the following error. 
```
Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
```
Aside from changing the build configuration of this project, these changes are an unobtrusive way to support ESM-style Node projects. This PR will possibly close https://github.com/moment/luxon/issues/252 too.
> Add support for ESM-style Node imports

- src/impl/zoneUtil.js
- test/datetime/zone.test.js
- test/info/zones.test.js
**What is this about:**
The original issue that led to creating this PR was `setZone('system')` is using the Timezone in `Settings.defaultZone`, not the browser Timezone (https://github.com/moment/luxon/issues/1182), the name is pretty self-explanatory.
**Changes in this PR:**
- added a condition for `system` to return `SystemZone.instance` along with `local`
- added a condition for `defaultZone` to accept also `default` parameter
- Fixed deprecated tests that took local zone as default while setting non-system one, as per "local" is a legacy name for "system"
- Add test for `setZone()` using the `system` zone
> Add condition for system setZone

- src/duration.js
Corrected typo in example documentation for .mapUnits
> Corrected typo in duration.js

- docs/formatting.md
As browsers upgrade to ICU 71, dates and times in `en_US` are combined with `at`, per https://github.com/unicode-org/cldr-json/blob/8d565de3afecd4dc3f82b3bdbc3336e2d588a350/cldr-json/cldr-dates-modern/main/en/ca-gregorian.json#L346-L347, as noted in https://github.com/tc39/ecma402/issues/665. 
E.g., on the latest versions of Chrome and Firefox, each of the below now output an `at`:
```js
> luxon.DateTime.now().toLocaleString(luxon.DateTime.DATETIME_FULL)
'July 31, 2022 at 9:50 AM EDT'
> luxon.DateTime.now().toLocaleString(luxon.DateTime. DATETIME_HUGE)
'Sunday, July 31, 2022 at 9:50 AM Eastern Daylight Time'
> luxon.DateTime.now().toLocaleString(luxon.DateTime. DATETIME_FULL_WITH_SECONDS)
'July 31, 2022 at 9:50:00 AM EDT'
> luxon.DateTime.now().toLocaleString(luxon.DateTime. …
```
> Adds 'at' to FULL and HUGE examples for en_US

- docs/parsing.md
I could not find a location within the docs where it explains the escape/literal syntax for `fromFormat` when literal values are included in the parsed string (e.g. `T` in `2022-03-15T11:11:11.111Z`). I was able to figure it out by looking at the tests in [`tokenParse.test.js`](https://github.com/moment/luxon/blob/master/test/datetime/tokenParse.test.js#L569), so thought I would bubble it up into the docs for other users.
Added a row to the token table explaining `'` is the token for starting and ending a literal. Albeit this a little weird as the literals aren't technically tokens, but `'` technically is. I can move it to be a part of the paragraph if the core maintainers prefer this. Just let me know!
> Update parsing docs to show syntax for literals

- src/duration.js
- test/datetime/math.test.js
- test/duration/customMatrix.test.js
Duration for businesses days are not calendar durations. Meaning that a day is 7 or 8 hours of work and a week probably 5 days.
So if I say a task is going to take 2 days, it means 16 hours of work.
In order to solve that I've added the support for custom matrix for `Duration`. Doing so the `shiftTo` method can transform units as we want it to.
There is a problem is with `DateTime.plus()`. I have noticed it shifts everything to milliseconds to move the clock forward. While I understand why, it raises an issue because it doesn't account for the leap in time between days for exemple. 
`2 days means 14 hours means 840 minutes means 50400 seconds means 50,400,000 millis` according to the duration matrix.
However if you add 2 days to `2022-06-15 05:00` you expect it to move forwards to …
> Duration support custom matrix

- package.json
This PR fixes the compatibility between react-native and the last `luxon` versions (broken since [v2.5.0](https://github.com/moment/luxon/releases/tag/2.5.0)).
It adds the `package.json` to the exports section
```diff
"exports": {
".": {
"import": "./src/luxon.js",
"require": "./build/node/luxon.js"
},
+   "./package.json": "./package.json",
},
```
It is something you can find in other popular libraries that have to deal with multiple js environments and bundlers, such as `react-native`.
Something similar happened to the [`uuidjs/uuid`](https://github.com/uuidjs/uuid) repository:
- [Issue](https://github.com/uuidjs/uuid/issues/444)
- [PR](https://github.com/uuidjs/uuid/pull/449)
- [Release](https://github.com/uuidjs/uuid/blob/16e9cc9017663a24588c4925bb3e63ae624ad1d4/CHANGELOG.md#bug-fixes- …
> [package.json] Add ./package.json to exports

- src/impl/diff.js
Resolves https://github.com/moment/luxon/issues/1266
> DateTime.diff produces wrong results with unit quarter fix.

- docs/formatting.md
In #1262, the formatting docs were updated to include examples of the new formatting for `DATETIME_FULL` introduced in ICU 71; this PR updates another one of these examples included further up the page for consistency.
> Update text example of DATETIME_FULL formatting

- .github/workflows/test.yml
- src/duration.js
- test/duration/units.test.js
There's a use case right now where you have a duration from a set of units but want them to be displayed to the user in a more "human readable" format.
For example, you might want to display the duration between various 2 datetimes, which can defer in hours or just a few seconds:
```js
const dur = Interval.fromDateTimes(start, end).toDuration(['hours', 'minutes', 'seconds', 'milliseconds'])
console.log(dur.toHuman())
// example outputs:
// 4 hours, 0 minutes, 12 seconds and 0 milliseconds
// 0 hours, 0 minutes, 5 seconds and 0 milliseconds
// 0 hours, 54 minutes, 0 seconds and 0 milliseconds
```
Because the duration can vary greatly between just a few seconds and many hours, the current output is completely useless.
One would expect the `normalize()` method to solve this problem but …
> feat: add rescale option to Duration.normalize method

- src/impl/formatter.js
- src/interval.js
- test/interval/format.test.js
Hi,
`Interval.toLocaleString(formatOpts, opts)` works like `DateTime.toLocaleString(formatOpts, opts)`. Example:
```js
Interval.fromISO('2022-11-07T09:00Z/2022-11-08T09:00Z').toLocaleString(DateTime.DATE_FULL, { locale: 'fr-FR' });
//=> 7–8 novembre 2022
```
It relies on `Intl.DateTimeFormat.formatRange()`, now [well supported by browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRange#browser_compatibility).
Partly closes [luxon/issues#1237](https://github.com/moment/luxon/issues/1237) (I can add `toLocaleParts` in this PR or a different one). Closes [luxon/issues#691](https://github.com/moment/luxon/issues/325).
> Add Interval.toLocaleString()

- CONTRIBUTING.md
- src/impl/locale.js
- test/datetime/create.test.js
- test/datetime/format.test.js
Fixes: https://github.com/moment/luxon/issues/1335
> preserve language tags

- src/impl/util.js
- test/datetime/math.test.js
Fixes #1389
From [#1389](https://github.com/moment/luxon/issues/1389#issuecomment-1443392279):
> The problem here is not `diff`, but actually `plus`:
`DateTime.fromISO('0099-12-31', {zone: "utc"}).plus({days: 61}).toISODate()` produces `0100-03-01`, not `0100-03-02`. What is happening is that deep inside Luxon it calls `Date.UTC` with a computed date object (day, month, etc.). `Date.UTC` however treats years before 100 as 19XX. So year 99 turns into 1999. Luxon works around this by checking if the year is < 100 and if so, using `setUTCFullYear` afterwards. Here is the problem: year 2000 is a leap year, year 100 is not. So if you do a plus operation that goes from year 99 into year 100, the native JavaScript Date object thinks it is crossing from year 1999 into year 2000 - and year 2000 is …
> Handle dates in year 99 rolling over into year 100 better

- .github/workflows/test.yml
- src/impl/formatter.js
- src/impl/tokenParser.js
- test/datetime/format.test.js
- test/datetime/toFormat.test.js
- test/datetime/tokenParse.test.js
- test/interval/format.test.js
> Fix support for Node.js 18.13+

- docs/formatting.md
I noticed that #1114 introduced `toUnixInteger()` but it wasn't included in the documentation.
> Add toUnixInteger() to the formatting documentation.

- src/impl/locale.js
- test/datetime/format.test.js
This addresses https://github.com/moment/luxon/issues/1363
This addresses a couple of bugs related to non-IANA timezone formatting
* timezones can be displayed even if `timeZoneName` is not set and partial hour fixed-offset zones don't handle this properly
* non-universal custom non-IANA zones are treated as IANA zones and are improperly formatted
* allow all zones to have timezone in the format using `formatToParts`
> Custom zone formatting support

- docs/install.md
- docs/matrix.md
Resurrecting #609 which was closed because the original author @roadmanfong didn't sign the CLA.
Have revised the wording, and simplified the diff for configuring jsc build flavor.
> Update docs on react native android support

- src/interval.js
- test/interval/info.test.js
Fixes #1306
One of the tests actually tested this incorrect behavior, which I have adjusted. I have also added a new test, explicitly testing the correct behavior.
> Fix Interval#count counting the endpoint as part of the interval

- docs/zones.md
`defaultZone` is readonly.
Current example leads to "Cannot assign to 'defaultZone' because it is a read-only property.ts (2540)". 
Change by setting `defaultZoneName` instead.
> zones.md: assign to defaultZoneName

- src/datetime.js
- src/duration.js
- test/datetime/format.test.js
- test/duration/format.test.js
I have created this as a pull request, because _technically_ this is a breaking change.
Previously `DateTime#toISOTime` would ignore milliseconds even if only `suppressSeconds` was set. `Duration#toISOTime` did not do so. I have aligned the behavior between the two, so that no data is ever silently ignored (suppressing only works if _all_ hidden units are 0).
Please let me know if you think preserving the original behavior of suppressSeconds on DateTime is worthwhile. 
Fixes #1403
> Fix Duration#toISOTime depending on the locale

- src/impl/formatter.js
- src/impl/tokenParser.js
- test/datetime/tokenParse.test.js
When expanding macro tokens, we must expand "hour" either into "h" or "H", depending on the desired hour cycle. 
This fixes #1197.
I have not changed the parsing of `h`, which currently accepts 24 hours just the same as `H`. This would be a breaking change and I am not sure it is worth introducing another special case in the parser for this.
> Correctly handle hourCycle when expanding macro tokens

- docs/math.md
Small change to the docs. Presumably the word `leap` is missing in the sentence "**Years** vary because of years".
> [docs] Add missing "leap" in "leap years"

- src/datetime.js
the @param as {DateTime} was incorrect and while it technically accepts {string|Invalid}, looking at the code and original documentation lended the impression you'd prefer a string argument for the public API docs
> Update datetime.js documentation

- src/duration.js
- test/duration/units.test.js
Continuing https://github.com/moment/luxon/pull/1296/commits/1b735939d319990e53ed440aaa3a41456488c960
Fix #1233 as well as https://github.com/moment/luxon/issues/781#issuecomment-1008051278
Values like `{ hours: 96, minutes: 0, seconds: -10 }`  will be normalized to  `{ hours: 95, minutes: 59, seconds: 50 }`
This behavior is consistent with `rescale()`
Test case provided as per https://github.com/moment/luxon/pull/1296#issuecomment-1267456483
> Fix normalize() to handle partially negative inputs

- src/impl/locale.js
- test/info/listers.test.js
`Info.months()` for Islamic has duplicate month "**Rabiʻ I**" and also Islamic months' order is incorrect.
Fixed by changing the year from 2016 to 2009 which is the most recent year that Islamic and Gregorian months are sync.
[Islamic months and their order](https://en.wikipedia.org/wiki/Islamic_calendar#Months)
> fix: Info.months for Islamic calendar

- src/impl/zoneUtil.js
Fixes #1426
`normalizeZone` uses `offset` on a Zone for the duck test, but incorrectly assumes it is a property that returns a number when in fact it is a function/method on Zone.
The duck test is particularly important for scenarios where package dependencies brought in their own copy of luxon (perhaps due to version mismatches), causing the `instance of` check to fail.  The duck test helps ensure compatibility with other instances of luxon modules.
> Fix duck test to match Zone interface

- src/impl/locale.js
- src/impl/tokenParser.js
`listingMode` function was being passed `defaultOK` to, but this function doesn't accept any arguments since 22/12/2021 (c96b8132).
> refactor: remove unused `defaultOK` parameter

- docs/parsing.md
One-liner change. Spent a while trying to figure out why I couldn't use fromFormat with `TTT`, and ended up being not supported by the function even though it's in the parsing table of valid tokens, which may be confusing, albeit also already stating that `Luxon also doesn't support the "macro" tokens that include offset names, such as "ttt" and "FFFF"`.
> Fix: Remove "TTT" from valid parsing tokens

- src/duration.js
- test/duration/invalid.test.js
Fixes #1488 
I've also added tests so that this behavior is no longer broken in the future.
@icambron It would be good to get this out as 3.4.1 relatively quickly, considering this is a regression.
> Handle invalid Durations in toHuman and toMillis

- src/duration.js
- src/impl/util.js
Fixes #1493
In the process of fixing this, I have updated the algorithm used in `normalizeValues` to make it more clear what it actually does and improved the documentation for `Duration#normalize` to clarify what "canonical representation" means.
Additionally, I have removed the broken implementation of `convert` that was introduced in #1467. After the refactoring of `normalizeValues`, `Duration#shiftTo` was the only user of `convert`, and unnecessarily so. shiftTo used convert to perform some of the same steps that normalize already does, which shiftTo calls afterwards. As such `convert` has been removed.
> Fix and improve `Duration#normalize`

- src/duration.js
- test/duration/units.test.js
This fixes #1496 by introducing an additional conversion step in `Duration#normalize` / `normalizeValues`.
This step converts any fractions in larger units into lower units, if possible. 
For example: `{ years: 2.5, days: 0, hours: 0 }` becomes `{ years: 2, days: 182, hours: 12 }` (assuming casual conversions).
This also affects `shiftTo` and `shiftToAll`. I have added tests for all three methods to test this behavior.
Note: This alters the behavior of `normalize`, because previously `normalize` would not do this. `{years: 2.5, days: 0}` would stay as-is. I would argue that that is a bug however, which is fixed by this pull request. `shiftTo` (and by extension `shiftToAll`) _did_ do this, prior to calling `normalize`, however I would argue that this is something that should be handled by …
> Fix Duration#normalize, shiftTo and shiftToAll

- src/duration.js
There appears to be a very small typo in the docstrings for `Duration.normalize()`. The docstring mentions negative values, but points to an example about excessive values, whereas the _third_ example appears to exemplify the point made in the docstring.
> Fix docstring example reference

- docs/formatting.md
- docs/intl.md
- src/datetime.js
- src/duration.js
- src/impl/conversions.js
- src/impl/formatter.js
- src/impl/locale.js
- src/impl/util.js
- src/info.js
- src/interval.js
- src/settings.js
- test/datetime/create.test.js
- test/datetime/localeWeek.test.js
- test/datetime/set.test.js
- test/datetime/toFormat.test.js
- test/helpers.js
- test/info/features.test.js
- test/info/localeWeek.test.js
- test/interval/localeWeek.test.js
Use [`Intl.Locale#getWeekInfo`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getWeekInfo) to provide locale-dependent week information, such as the start of the week.
Fixes #1447
> Implement localized week information

- src/interval.js
- test/interval/many.test.js
`Interval#splitAt` is incorrectly sorting the input `DateTime`s by ISO strings (`Array.sort` implicitly calls `toString`), which leads to invalid intervals when trying to split at DST shifted hours.
This PR changes the sorting to use the underlying epoch milliseconds instead.
> Fix Interval.splitAt datetime sorting

- src/duration.js
The `Duration#toHuman` docblock is currently quite unclear as to where `listStyle` comes from, which hopefully this improves.
> Improve Duration#toHuman docblock

- src/datetime.js
- src/duration.js
- src/interval.js
Adds back the custom inspection functions for node.js, first added by #281 then removed by #318 and [55ac17e]. This change avoids the default node's object inspection listing all fields recursively. This time there are no node imports or any run-time dependency. We simply expose the inspect functions as symbol-named attribute `Symbol.for('nodejs.util.inspect.custom')` as described in the [docs](https://nodejs.org/api/util.html#utilinspectcustom).
Note: I've simplified the formats from the original addition to make it single line and simpler.
* npm run build
* npm run format-check
* ./scripts/test
* Manual
```
const { DateTime, Duration, Interval } = require('./build/cjs-browser/luxon')
Duration.fromObject({ seconds: 10 })
Interval.fromDateTimes(DateTime.now().minus({ days: 1 }), …
```
> Add custom inspect for node without depedency

- src/datetime.js
- test/datetime/invalid.test.js
Fixes #1449.
So the issue here is that whenever the year passed is too big, `DateTime.fromObject` goes all the way through execution and ends up returning the DateTime instance.
The instance, which is being instantiated [here](https://github.com/moment/luxon/blob/master/src/datetime.js#L798), is invalid. This is because DateTime's constructor checks on the year [here](https://github.com/moment/luxon/blob/master/src/datetime.js#L492) and assigns `invalid`. The problem is that, unlike other invalid cases, in this one (and probably others) we never go through `DateTime.invalid`, therefore we do not check on `throwIfInvalid` (and eventually throw).
So here I'm checking if the DateTime instance is invalid before returning, and if it is, i'm going through the same `DateTime.invalid` method. …
> fix: DateTime throws when year is invalid and throwOnInvalid is true

- docs/calendars.md
In reference to #1540 
- Added the commonly used calendar `islamic-umalqura` to the table
- Added link to MDN page to see all available calendars
- There is a deprecation notice on the MDN page for the `islamicc` calendar. Updated it in the table to `islamic-civil`  as recommended.
> Docs: Enhance supported calendars section

- src/datetime.js
- test/datetime/invalid.test.js
We validate the zone in the constructor anyway, but the tests missed a branch where we attempt to use an invalid zone to compute an offset, which will result in an exception. Zone#isValid is calculated at creation time (and checked in DateTime constructor already) so this will not degrade performance in the happy case.
We discovered this when shifting callsites to use `DateTime.local` from things that previously called through `fromObject`.
> Validate time zone in quickDT prior to guessing offset

- test/datetime/proto.test.js
- test/duration/proto.test.js
- test/interval/proto.test.js
Debian checks what happens with running `node --disable-proto=throw`.
Because __proto__ brings so many trivial-to-exploit security issues, we might disable-proto by default.
Here it's just used in the tests, nonetheless, it's an old js feature that might just be phased out, hopefully.
> Use getPrototypeOf instead of __proto__

- src/impl/digits.js
- src/settings.js
Profiles reveal that a substantial portion of fromFormat time is spent in digitsRegex. It is only called from unitsForToken and it is always called with 11 suffixes to match different numbers of digits.
There are 21 numbering systems, so a fully expanded cache would hold 11*21 = 231 regexes.
This is related to https://github.com/moment/luxon/pull/1530 , but involves a much more restricted cache
Benchmark Comparison (`name | before | after | after/before`):
```
DateTime.fromFormat | 60,666 ±0.17% | 113,218 ±0.20% | 1.87x
DateTime.fromFormat with zone | 26,687 ±0.18% | 33,563 ±0.19% | 1.26x
```
> Perf: Memoize digitsRegex

- benchmarks/datetime.js
- src/datetime.js
- src/impl/locale.js
- src/impl/tokenParser.js
- test/datetime/tokenParse.test.js
This allows constructing a parser for a locale/format and reusing it when parsing dates. Without this, DateTime.fromFormat constructs a new parser on every call. When parsing large amounts of date strings, this gets rather slow.
Benchmark Comparison (`name | before | after | after/before`):
```
DateTime.fromFormat | 60,666 ±0.17% | 61,000 ±0.17% | ~
DateTime.fromFormat with zone | 26,687 ±0.18% | 26,688 ±0.21% | ~
DateTime.fromFormatParser |		| 402,199 ±0.13%
DateTime.fromFormatParser with zone |		| 45,206 ±0.22%
fromFormat vs. fromFormatParser | 60,666 ±0.17% | 402,199 ±0.13% | 6.63x
fromFormat vs …
```
> Perf: Add DateTime.buildFormatParser and DateTime.fromFormatParser

- benchmarks/datetime.js
- src/datetime.js
_This includes the commit from https://github.com/moment/luxon/pull/1574 to establish the benchmark_
All calls to the datetime constructor that pass an offset (o), have just
computed that offset (quickDT, fromObject) except for clone(). Clone
passes an "old" option to determine whether previous offset can be
reused. If we have config.o, but config.old is not set, then we can use
o without computing it.
This saves an expensive call to zone.offset that duplicates work that
was done immediately prior.
Benchmark Comparison (`name | before | after | after/before`):
```
DateTime.fromObject with locale | …
```
> Perf: Use computed offset passed in DateTime constructor

- benchmarks/datetime.js
We found that time zone handling took up a lot of time. This adds a benchmark around this for `DateTime.local` (which uses `quickDT` and is the fastest path for creating DateTimes from date components. This also renames the existing `DateTime.local` benchmark to be `DateTIme.now` as it calls `DateTime.now` rather than `local`
```
DateTime.now x 3,076,386 ops/sec ±0.16% (98 runs sampled)
DateTime.fromObject with locale x 1,112,953 ops/sec ±0.08% (99 runs sampled)
DateTime.local with numbers x 844,898 ops/sec ±0.15% (100 runs sampled)
DateTime.local with numbers and zone x 50,913 ops/sec ±0.18% (97 runs …
```
> Perf: Add benchmark for DateTime.local with zone

- site/index.html
All examples use `DateTime`. The install guide even suggests doing the alias.
The first thing I tried was to copy the example on the landing page `DateTime.now().setZone('America/New_York').minus({weeks:1}).endOf('day').toISO();`
->
`Uncaught ReferenceError: DateTime is not defined at <anonymous>:1:1`
> Alias DateTime in documentation site

- src/datetime.js
- src/settings.js
- test/datetime/dst.test.js
- test/datetime/regexParse.test.js
_This includes the commit from https://github.com/moment/luxon/pull/1574 to establish the benchmark_
Previously we guessed by calling zone.offset(tsNow) on every
construction of a date from date parts. This caches that result instead,
saving a call to offset. The tests verify that this works across DST boundaries when the cache holds an offset for the previous DST state from now.
For processes that live across a DST boundary and mostly handle current date times, this will mean the guess is wrong and we'll have to re-guess. Since we're caching one call to offset, this should be performance neutral to …
> Perf: Cache ts offset guesses for quickDT

- src/datetime.js
Added weekSettings option in the doc for the following methods in DateTime
1. fromMillis
2. fromSeconds
3. fromObject
4. fromISO
5. fromRFC2822
6. fromHTTP
7. fromFormat
8. fromSQL
> Documented weekSettings opt in DateTime

- src/interval.js
Convenient way to get the last moment that is actually included in the interval. Makes it easier to properly use the fact that intervals are half open.
My use case: displaying end date of a monthly subscription.
I'm not sure `lastMoment` is the best way to name this, but it was the first thing that I thought of.
> Add lastMoment getter to Interval

- src/datetime.js
`toISODate` method could return `null` even if it is not explicit in the method type.
```typescript
import { DateTime } from "luxon";
const invalidDate = new Date('2023-15-56'); // -> InvalidDate
const dt = DateTime.fromJSDate(invalidDate) // -> DateTime
const isoDt = dt.toISODate(); // -> null
```
A pull request for [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) is already opened in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64919
> fix: toISODate, toISO and toSQLDate methods could return null when an InvalidDate is provided

- src/datetime.js
DateTime.until returns Interval or DateTime conditionally.
It is already on the [type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ec2fdb5dc09bcd3a871a46212c5f611b6cdd3a1c/types/luxon/src/datetime.d.ts#L1527) but luxon documentation is wrong with it.
> docs: until returns Inverval or DateTime conditionally

- benchmarks/datetime.js
- src/impl/locale.js
* **Caching:** Implemented caching to avoid redundant computations of resolved options and locale parsing.
* **Efficient Checks:** Introduced a final isEnglish variable to efficiently determine if the locale supports English.
* **Initialization**: supportsFastNumbers is now immediately initialized to prevent unnecessary calls.
Tests indicate up to a 10x speed improvement with these enhancements.
Fixes #1428
> Optimize Performance with Caching for Resolved Options and Parsed Locale Strings

- src/datetime.js
Relevant discussion here: https://github.com/moment/luxon/issues/565
Newest discussion was brought up again here, indicating users are still having issues with toSeconds() returning the milliseconds as the floating point part of the number: https://github.com/moment/luxon/issues/1644
I've updated the doc string to match the toUnixInteger's format of indicating it returns a floating point instead of a whole number.
> Include documentation that toSeconds() returns a floating point number

- .github/workflows/test.yml
- test/datetime/tokenParse.test.js
- test/helpers.js
CLDR 46 makes changes to the kn (Kannada) and ta (Tamil) locales effectively disregarding local names for AM/PM (Kannada) and special names for afternoon. The tests have been modified to use "PM".
Fixes #1675
> Modify tokenParser tests to suit CLDR 46

- src/impl/regexParser.js
- test/datetime/regexParse.test.js
I've added the unit tests requested in the discussion on benjamin-pike's [PR #1624](https://github.com/moment/luxon/pull/1624)
Adds the ability for DateTime.fromISO to parse ISO strings containing lowercase t and z characters.
Resolves https://github.com/moment/luxon/issues/1610
> add lowercase t and z to ISO parsing regexes and unit tests

- src/datetime.js
- src/impl/util.js
- test/datetime/relative.test.js
This PR fully address the issue described in #1129 (and fully replace PR #1683) by introducing an additional `rounding` option. This PR is fully backward compatible.
Before this PR, the only option for rounding with `toRelative()` is to rounds towards zero.
With this PR, I add a new parameter `rounding` who can be `"trunc"` (towards zero), `"expand"` (away from zero), `"round"`, `"floor"`, or `"ceil"` to address all options. The `rounding` option works with `round: true` and `round: false`.
I'm open for better names for `"towardsZero"`, `"awayFromZero"`. 
Fixes #1129.
> Rounding options to toRelative

- package.json
Currently it seems that Metro (from React Native) isn't resolving Luxon correctly due to the incorrect exports configuration. 
It seems that ESM imports prefer the source code instead of the built code. Changing this to the es6 build resolves the issue.
This is the error with the old export:
> build: use the es6 build for ESM exports

- src/zones/IANAZone.js
- test/zones/IANA.test.js
Addressing #1717 
Adds following implementation to get canonical IANA timezone name, instead of just using user provided casing.
```js
const dtf = new Intl.DateTimeFormat("en-US", { timeZone: name });
this.zoneName = dtf.resolvedOptions().timeZone;
```
Added a test "`IANAZone returns canonical zone name regardless of input casing`" which passes the implementation.
> IANAZone returns the canonical IANA zone name; Test included in IANA.test.js

- src/datetime.js
- test/datetime/format.test.js
with `format: 'basic'` option, `toISO` and `toISOTime` is supposed to return techie offset (ex. `+0900`)
https://github.com/moment/luxon/blob/3e9983cd0680fdf7836fcee638d34e3edc682380/src/datetime.js#L1825
but, it returns short offset (ex. `+09:00`) with `:` instead.
```js
% node
Welcome to Node.js v22.3.0.
Type ".help" for more information.
> const { DateTime } = await import("luxon");
undefined
> DateTime.now().toISO({ format: 'basic' });
'20241003T231708.609+09:00'
```
> Use techie offset for basic ISO format
